### ISSUE TITLE
amdgpu: Kernel panic on loading: malloc: called with spinlock or critical section held

### ISSUE THREAD

**Issue by neelchauhan** [freebsd/drm-kmod#101]
**Describe the bug**

When I attempt to load `amdgpu` on an HP Envy x360 with AMD Ryzen 7 4700U, it goes to a blank screen and then get an `panic: malloc: called with spinlock or critical section held`.

This happens on the Ports 5.5 and the 5.6-wip branch where Renior should be supported (unlike my previous now-sold TigerLake HP Spectre).

**FreeBSD version**

    FreeBSD envy.local 14.0-CURRENT FreeBSD 14.0-CURRENT #0 main-n248478-f3a3b061216: Thu Aug  5 06:53:04 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

**PCI Info**

    hostb0@pci0:0:0:0:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1630 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Root Complex'
        class      = bridge
        subclass   = HOST-PCI
    none0@pci0:0:0:2:    class=0x080600 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1631 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir IOMMU'
        class      = base peripheral
        subclass   = IOMMU
    hostb1@pci0:0:1:0:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1632 subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir PCIe Dummy Host Bridge'
        class      = bridge
        subclass   = HOST-PCI
    pcib1@pci0:0:1:3:    class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1634 subvendor=0x1022 subdevice=0x1453
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir PCIe GPP Bridge'
        class      = bridge
        subclass   = PCI-PCI
    hostb2@pci0:0:2:0:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1632 subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir PCIe Dummy Host Bridge'
        class      = bridge
        subclass   = HOST-PCI
    pcib2@pci0:0:2:1:    class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1634 subvendor=0x1022 subdevice=0x1453
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir PCIe GPP Bridge'
        class      = bridge
        subclass   = PCI-PCI
    pcib3@pci0:0:2:3:    class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1634 subvendor=0x1022 subdevice=0x1453
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir PCIe GPP Bridge'
        class      = bridge
        subclass   = PCI-PCI
    hostb3@pci0:0:8:0:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1632 subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir PCIe Dummy Host Bridge'
        class      = bridge
        subclass   = HOST-PCI
    pcib4@pci0:0:8:1:    class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1635 subvendor=0x1022 subdevice=0x1635
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Internal PCIe GPP Bridge to Bus'
        class      = bridge
        subclass   = PCI-PCI
    intsmb0@pci0:0:20:0:    class=0x0c0500 rev=0x51 hdr=0x00 vendor=0x1022 device=0x790b subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'FCH SMBus Controller'
        class      = serial bus
        subclass   = SMBus
    none1@pci0:0:20:3:    class=0x060100 rev=0x51 hdr=0x00 vendor=0x1022 device=0x790e subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'FCH LPC Bridge'
        class      = bridge
        subclass   = PCI-ISA
    hostb4@pci0:0:24:0:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1448 subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 0'
        class      = bridge
        subclass   = HOST-PCI
    hostb5@pci0:0:24:1:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1449 subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 1'
        class      = bridge
        subclass   = HOST-PCI
    hostb6@pci0:0:24:2:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x144a subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 2'
        class      = bridge
        subclass   = HOST-PCI
    hostb7@pci0:0:24:3:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x144b subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 3'
        class      = bridge
        subclass   = HOST-PCI
    hostb8@pci0:0:24:4:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x144c subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 4'
        class      = bridge
        subclass   = HOST-PCI
    hostb9@pci0:0:24:5:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x144d subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 5'
        class      = bridge
        subclass   = HOST-PCI
    hostb10@pci0:0:24:6:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x144e subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 6'
        class      = bridge
        subclass   = HOST-PCI
    hostb11@pci0:0:24:7:    class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x144f subvendor=0x0000 subdevice=0x0000
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir Device 24: Function 7'
        class      = bridge
        subclass   = HOST-PCI
    none2@pci0:1:0:0:    class=0x028000 rev=0x1a hdr=0x00 vendor=0x8086 device=0x2723 subvendor=0x8086 subdevice=0x0084
        vendor     = 'Intel Corporation'
        device     = 'Wi-Fi 6 AX200'
        class      = network
    rtsx0@pci0:2:0:0:    class=0xff0000 rev=0x01 hdr=0x00 vendor=0x10ec device=0x522a subvendor=0x103c subdevice=0x876e
        vendor     = 'Realtek Semiconductor Co., Ltd.'
        device     = 'RTS522A PCI Express Card Reader'
    nvme0@pci0:3:0:0:    class=0x010802 rev=0x00 hdr=0x00 vendor=0x15b7 device=0x5006 subvendor=0x15b7 subdevice=0x5006
        vendor     = 'Sandisk Corp'
        device     = 'WD Black SN750 / PC SN730 NVMe SSD'
        class      = mass storage
        subclass   = NVM
    vgapci0@pci0:4:0:0:    class=0x030000 rev=0xc2 hdr=0x00 vendor=0x1002 device=0x1636 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
        device     = 'Renoir'
        class      = display
        subclass   = VGA
    hdac0@pci0:4:0:1:    class=0x040300 rev=0x00 hdr=0x00 vendor=0x1002 device=0x1637 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
        device     = 'Renoir Radeon High Definition Audio Controller'
        class      = multimedia
        subclass   = HDA
    none3@pci0:4:0:2:    class=0x108000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x15df subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Family 17h (Models 10h-1fh) Platform Security Processor'
        class      = encrypt/decrypt
    xhci0@pci0:4:0:3:    class=0x0c0330 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1639 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir USB 3.1'
        class      = serial bus
        subclass   = USB
    xhci1@pci0:4:0:4:    class=0x0c0330 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1639 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Renoir USB 3.1'
        class      = serial bus
        subclass   = USB
    none4@pci0:4:0:5:    class=0x048000 rev=0x01 hdr=0x00 vendor=0x1022 device=0x15e2 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Raven/Raven2/FireFlight/Renoir Audio Processor'
        class      = multimedia
    hdac1@pci0:4:0:6:    class=0x040300 rev=0x00 hdr=0x00 vendor=0x1022 device=0x15e3 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Family 17h (Models 10h-1fh) HD Audio Controller'
        class      = multimedia
        subclass   = HDA
    none5@pci0:4:0:7:    class=0x118000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x15e4 subvendor=0x103c subdevice=0x876e
        vendor     = 'Advanced Micro Devices, Inc. [AMD]'
        device     = 'Raven/Raven2/Renoir Sensor Fusion Hub'
        class      = dasp

**DRM KMOD version**

Happens on Ports `5.5.19.g20210709` and `5.6-wip`

**To Reproduce**
Take an HP Envy x360 with AMD Ryzen 4700U (or any DCN21 GPU), and load `amdgpu`. It should go to a blank screen and panic.

**Screenshots**
N/A - blank screen

**Additional context**

Stacktrace:

    Unread portion of the kernel message buffer:
    taskqueue_drain with the following non-sleepable locks held:
    exclusive sleep mutex vtdev (vtdev) r = 0 (0xffffffff81aea0a8) locked @ /usr/src/sys/dev/vt/vt_core.c:3012
    stack backtrace:
    #0 0xffffffff80c902e1 at witnespanic: malloc: called with spinlock or critical section held
    cpuid = 6
    time = 1628439111
    KDB: stack backtrace:
    db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe00c1ff4470
    vpanic() at vpanic+0x187/frame 0xfffffe00c1ff44d0
    panic() at panic+0x43/frame 0xfffffe00c1ff4530
    malloc_dbg() at malloc_dbg+0xe2/frame 0xfffffe00c1ff4550
    malloc() at malloc+0x30/frame 0xfffffe00c1ff45a0
    dcn21_validate_bandwidth() at dcn21_validate_bandwidth+0x7e/frame 0xfffffe00c1ff4630
    dc_validate_global_state() at dc_validate_global_state+0x2cc/frame 0xfffffe00c1ff4690
    amdgpu_dm_atomic_check() at amdgpu_dm_atomic_check+0xee1/frame 0xfffffe00c1ff4940
    drm_atomic_check_only() at drm_atomic_check_only+0x424/frame 0xfffffe00c1ff49c0
    drm_atomic_commit() at drm_atomic_commit+0x13/frame 0xfffffe00c1ff49e0
    drm_client_modeset_commit_atomic() at drm_client_modeset_commit_atomic+0x148/frame 0xfffffe00c1ff4a50
    drm_client_modeset_commit_force() at drm_client_modeset_commit_force+0x66/frame 0xfffffe00c1ff4a90
    drm_fb_helper_restore_fbdev_mode_unlocked() at drm_fb_helper_restore_fbdev_mode_unlocked+0x7a/frame 0xfffffe00c1ff4ac0
    taskqueue_run_locked() at taskqueue_run_locked+0xaa/frame 0xfffffe00c1ff4b40
    taskqueue_thread_loop() at taskqueue_thread_loop+0xc2/frame 0xfffffe00c1ff4b70
    fork_exit() at fork_exit+0x80/frame 0xfffffe00c1ff4bb0
    fork_trampoline() at fork_trampoline+0xe/frame 0xfffffe00c1ff4bb0

Stacktrace: [crash.log](https://github.com/freebsd/drm-kmod/files/6951746/crash.log)

**Comment by unrelentingtech** [comment]
The critical section in bandwidth validation must be the FPU one… as of https://reviews.freebsd.org/D29921

This FPU stuff was a complete mess upstream and the malloc issue is only fixed in https://github.com/torvalds/linux/commit/680174cfd1e1cea70a8f30ccb44d8fbdf996018e / https://github.com/torvalds/linux/commit/f41ed88cbd6f025f7a683a11a74f901555fba11c

But the thing is, `dcn21_validate_bandwidth` in 5.5/5.6 really shouldn't malloc inside an FPU block (only dcn20 should), so maybe something left an FPU block still open…??

Try logging all that stuff (and also cleaning up leftover direct ifdef'd `kernel_fpu` calls), this is for v5.6-wip:

```diff
diff --git i/drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c w/drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c
index 443255335b..b441a20109 100644
--- i/drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c
+++ w/drivers/gpu/drm/amd/display/dc/dcn20/dcn20_resource.c
@@ -3047,9 +3047,6 @@ bool dcn20_validate_bandwidth(struct dc *dc, struct dc_state *context,
 	bool dummy_pstate_supported = false;
 	double p_state_latency_us;
 
-#ifdef __FreeBSD__
-	kernel_fpu_begin();
-#endif
 	DC_FP_START();
 	p_state_latency_us = context->bw_ctx.dml.soc.dram_clock_change_latency_us;
 	context->bw_ctx.dml.soc.disable_dram_clock_change_vactive_support =
@@ -3057,9 +3054,6 @@ bool dcn20_validate_bandwidth(struct dc *dc, struct dc_state *context,
 
 	if (fast_validate) {
 		voltage_supported = dcn20_validate_bandwidth_internal(dc, context, true);
-#ifdef __FreeBSD__
-		kernel_fpu_end();
-#endif
 		DC_FP_END();
 		return voltage_supported;
 	}
@@ -3614,9 +3608,6 @@ static bool dcn20_resource_construct(
 	enum dml_project dml_project_version =
 			get_dml_project_version(ctx->asic_id.hw_internal_rev);
 
-#ifdef __FreeBSD__
-	kernel_fpu_begin();
-#endif
 	DC_FP_START();
 
 	ctx->dc_bios->regs = &bios_regs;
@@ -3921,9 +3912,6 @@ static bool dcn20_resource_construct(
 
 create_fail:
 
-#ifdef __FreeBSD__
-	kernel_fpu_end();
-#endif
 	DC_FP_END();
 	dcn20_resource_destruct(pool);
 
diff --git i/drivers/gpu/drm/amd/display/dc/os_types.h w/drivers/gpu/drm/amd/display/dc/os_types.h
index c34eba1986..b781e17789 100644
--- i/drivers/gpu/drm/amd/display/dc/os_types.h
+++ w/drivers/gpu/drm/amd/display/dc/os_types.h
@@ -53,8 +53,10 @@
 #if defined(CONFIG_DRM_AMD_DC_DCN)
 #if defined(CONFIG_X86)
 #include <asm/fpu/api.h>
-#define DC_FP_START() kernel_fpu_begin()
-#define DC_FP_END() kernel_fpu_end()
+#define DC_FP_START() { DRM_WARN("FPU start @ %s:%d (%s)", __FILE__, __LINE__, __func__); \
+	kernel_fpu_begin(); }
+#define DC_FP_END() { DRM_WARN("FPU end @ %s:%d (%s)", __FILE__, __LINE__, __func__); \
+	kernel_fpu_end(); }
 #elif defined(CONFIG_PPC64)
 #include <asm/switch_to.h>
 #include <asm/cputable.h>
```

**Comment by unrelentingtech** [comment]
Yeah, so as @wulf7 said in the chat, even correctly using nowait mallocs, the `KASSERT` trips anyway and here's your panic.

Having to run a non-`INVARIANTS` kernel on new GPUs just for this is not acceptable, so we have to pick an option:

- fix the damn assertion to be conditional on `M_WAITOK` (or non-`M_NOWAIT`)
  - I'm not an expert, I have no idea if that's safe, or why the assertion is non-conditional currently (i.e. why the code treats critical sections differently from interrupts)
- abandon `NOCTX`, use a stored context again — but now that we're thread-safe, the context would have to be stored in LinuxKPI `current` as well, so another version bump… oh well
  - doing this as a workaround for *an assertion* feels wrong!
- add local `ifdef` patches to move the alloc out of the FPU section
  - also sucks obviously but the least intrusive option (it's literally just two allocation calls…)

I guess I'll go with the last one but I'd like to hear some opinions about these options.

**Comment by neelchauhan** [comment]
I think the last option is a good option also, we shouldn't complicate things too much...

**Comment by wulf7** [comment]
May be we can add `DC_FP_END` right before malloc() and `DC_FP_START` right after it?

**Comment by unrelentingtech** [comment]
@wulf7 yeah that's kinda what I meant by local patches. I'll go with that then.

**Comment by wulf7** [comment]
following free() requires to be guarded too. Or converted to async version.

**Comment by wulf7** [comment]
@neelchauhan Could you test both https://github.com/freebsd/drm-kmod/pull/103 and https://github.com/freebsd/drm-kmod/tree/5.6-wip for this INVARIANTS panic and for https://github.com/freebsd/drm-kmod/issues/105 panic?

**Comment by neelchauhan** [comment]
Sorry for the long delay. The patch works well for me.

Thanks for your work!

**Comment by wulf7** [comment]
> The patch works well for me.
Thanks!

Which one works?  #103 or https://github.com/freebsd/drm-kmod/tree/5.6-wip ?

**Comment by neelchauhan** [comment]
5.6-wip works.

**Comment by wulf7** [comment]
Awesome! Do you have opportunity to test 5.5-stable (#103) as well?

**Comment by neelchauhan** [comment]
Sorry for the extreme delay (again), 5.5-stable works as well.

**Comment by wulf7** [comment]
Thank you for testing and @unrelentingtech for fix
