### ISSUE TITLE
[double-panic] vt_window_switch tries to malloc

### ISSUE THREAD

**Issue by mizhka** [freebsd/drm-kmod#109]
**Describe the bug**
In case of panic, system tries to switch vt to console and it causes second panic in drm-kmod code. 
Tried 5.5-wip dated by May-2021 and 5.6-wip (latest, dated by begin Sep-2021).

**FreeBSD version**
FreeBSD tamagawa.unclebear.ru 14.0-CURRENT FreeBSD 14.0-CURRENT #3 main-n249221-5fcdc19a8111: Tue Sep  7 18:05:34 MSK 2021     root@tamagawa.unclebear.ru:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

**PCI Info**

<details>
  <summary>pciconf -lv</summary>

  vgapci0@pci0:5:0:0:     class=0x030000 rev=0xc2 hdr=0x00 vendor=0x1002 device=0x1636 subvendor=0x103c subdevice=0x8730
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Renoir'
    class      = display
    subclass   = VGA

</details>

**DRM KMOD version**
Installed by make install
commit d56d121f1b72b97c00f70d46753892c2b87d441f 

**To Reproduce**
Random panic. May be sysctl allow to reproduce it, but I didn't try.

**Screenshots**
```
Tracing pid 20596 tid 102618 td 0xfffffe014e351ac0
kdb_enter() at kdb_enter+0x37/frame 0xfffffe0157c72230
vpanic() at vpanic+0x1b2/frame 0xfffffe0157c72280
panic() at panic+0x43/frame 0xfffffe0157c722e0
malloc_dbg() at malloc_dbg+0xd4/frame 0xfffffe0157c72300
malloc() at malloc+0x30/frame 0xfffffe0157c72350
drm_atomic_state_alloc() at drm_atomic_state_alloc+0x39/frame 0xfffffe0157c72370
drm_client_modeset_commit_atomic() at drm_client_modeset_commit_atomic+0x31/frame 0xfffffe0157c723e0
drm_client_modeset_commit_force() at drm_client_modeset_commit_force+0x69/frame 0xfffffe0157c72430
drm_fb_helper_restore_fbdev_mode_unlocked() at drm_fb_helper_restore_fbdev_mode_unlocked+0x7a/frame 0xfffffe0157c72460
vt_kms_postswitch() at vt_kms_postswitch+0x167/frame 0xfffffe0157c72490
vt_window_switch() at vt_window_switch+0x122/frame 0xfffffe0157c724d0
vtterm_cngrab() at vtterm_cngrab+0x4f/frame 0xfffffe0157c724f0
cngrab() at cngrab+0x16/frame 0xfffffe0157c72510
vpanic() at vpanic+0xec/frame 0xfffffe0157c72560
panic() at panic+0x43/frame 0xfffffe0157c725c0
trap_fatal() at trap_fatal+0x387/frame 0xfffffe0157c72620
trap() at trap+0xa4/frame 0xfffffe0157c72730
calltrap() at calltrap+0x8/frame 0xfffffe0157c72730
--- trap 0x9, rip = 0xffffffff80d2ff15, rsp = 0xfffffe0157c72800, rbp = 0xfffffe0157c72800 ---
strncmp() at strncmp+0x15/frame 0xfffffe0157c72800
ifunit_ref() at ifunit_ref+0x79/frame 0xfffffe0157c72840
ifioctl() at ifioctl+0x77f/frame 0xfffffe0157c72940
kern_ioctl() at kern_ioctl+0x289/frame 0xfffffe0157c729b0
sys_ioctl() at sys_ioctl+0x12a/frame 0xfffffe0157c72a80
amd64_syscall() at amd64_syscall+0x12e/frame 0xfffffe0157c72bb0
fast_syscall_common() at fast_syscall_common+0xf8/frame 0xfffffe0157c72bb0
```
**Additional context**

**Comment by evadot** [comment]
Should be fixed with https://cgit.freebsd.org/src/commit/?id=c937a405bdce2fd12c534446a8cc9e5548dd27eb
Please re-open the issue if it's not.
