### ISSUE TITLE
[Solved] Kernel Panic on AMD Vega 6

### ISSUE THREAD

**Issue by x-shayan** [freebsd/drm-kmod#142]
Hi. thanks for your job.  I'm not sure that I'm asking in right place or not, cause I can't find your E-Mail.
well, I wanna get my AMD Vega 6 (Renior) to work. I searched in FreeBSD forums, someone told that I should compile drm-kmod onto FreeBSD 14.0-CURRENT. I'm trying to build v5.6-stable and v5.7-stable because the drm-current-kmod port from FreeBSD has kernel panic for me. 

but I'm getting the following error: 

![photo_2022-02-02_15-46-50](https://user-images.githubusercontent.com/66168679/152152162-368e2118-9c8f-48ca-b89c-2e7299897357.jpg)

Sorry, I have not GUI for copying pciconf or uname -a. but It is FreeBSD-14.0-CURRENT-amd64-20220127 build. 
I did it:

git clone -b 5.6-stable https://github.com/freebsd/drm-kmod
cd drm-kmod
make 
make install

**Comment by wulf7** [comment]
You should install drm-devel-kmod port rather then drm-current-kmod to get v5.7

**Comment by x-shayan** [comment]
oh, sorry I wrote wrong. the drm-current-kmod port can't detect my gpu.
drm-devel-kmod can, but gives me kernel panic.

**Comment by evadot** [comment]
5.5 and 5.6 branch aren't supported anymore.
Try master or 5.7
And if you also have a panic with thoses open a issue with all the details.
5.7-stable is know to compile fine on current.
Thanks.

**Comment by x-shayan** [comment]
thanks for your quick reply.
I compiled and installed 5.7-branch. when I run startxfce4 or startx, it panics again.


My Device:
Lenovo Ideapad Gaming 3 15ARH05 
AMD Ryzen 5 4600H with AMD Vega 6 (Renoir) Graphics and GTX-1650Ti

kldstat:
![IMG_20220202_180921](https://user-images.githubusercontent.com/66168679/152178884-d90af13f-6d0d-4893-8444-324c7d57a5e2.jpg)

pciconf of my gpu:
![IMG_20220202_181013](https://user-images.githubusercontent.com/66168679/152178991-355bfbc8-f88b-497a-a54f-798be39ef171.jpg)


dmesg: 

![IMG_20220202_181121](https://user-images.githubusercontent.com/66168679/152179113-5377b761-bc80-45c8-a670-deb3e286ca4b.jpg)

![IMG_20220202_181133](https://user-images.githubusercontent.com/66168679/152179174-5cc6a10e-a7ac-4d02-b014-a08e587403f7.jpg)
![IMG_20220202_181147](https://user-images.githubusercontent.com/66168679/152179227-e0e7c55e-7cf9-4057-abf9-0d59f2eec8ac.jpg)


panic details:

![IMG_20220202_180749](https://user-images.githubusercontent.com/66168679/152179403-4f394125-3dab-4f85-b5e8-9e4b8b0656db.jpg)

FreeBSD 14.0-CURRENT
I hope you help me and I'm sorry about that I can't send text logs

**Comment by x-shayan** [comment]
I suprised. It works now! cool! thank you very much. 
another little thing that, why amdgpu.ko can't automatically load at boot? 
I have kld_list="amdgpu" in /etc/rc.conf
