### ISSUE TITLE
No console output after kldload amdgpu

### ISSUE THREAD

**Issue by gldisater** [freebsd/drm-kmod#211]
**Describe the bug**
No console output after kldload amdgpu

**FreeBSD version**
FreeBSD ryzen-current 14.0-CURRENT FreeBSD 14.0-CURRENT #11 main-n258527-67f2a563bfca: Mon Oct 10 15:13:38 EDT 2022     root@ryzen-current:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

**PCI Info**

<details>
  <summary>pciconf -lv</summary>
  
hostb0@pci0:0:0:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1450 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Root Complex'
    class      = bridge
    subclass   = HOST-PCI
amdiommu0@pci0:0:0:2:	class=0x080600 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1451 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) I/O Memory Management Unit'
    class      = base peripheral
    subclass   = IOMMU
hostb1@pci0:0:1:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1452 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib1@pci0:0:1:1:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1453 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
pcib2@pci0:0:1:3:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1453 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
hostb2@pci0:0:2:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1452 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
hostb3@pci0:0:3:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1452 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib10@pci0:0:3:1:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1453 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
hostb4@pci0:0:4:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1452 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
hostb5@pci0:0:7:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1452 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib11@pci0:0:7:1:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1454 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Internal PCIe GPP Bridge 0 to Bus B'
    class      = bridge
    subclass   = PCI-PCI
hostb6@pci0:0:8:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1452 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib12@pci0:0:8:1:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1454 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Internal PCIe GPP Bridge 0 to Bus B'
    class      = bridge
    subclass   = PCI-PCI
intsmb0@pci0:0:20:0:	class=0x0c0500 rev=0x59 hdr=0x00 vendor=0x1022 device=0x790b subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'FCH SMBus Controller'
    class      = serial bus
    subclass   = SMBus
isab0@pci0:0:20:3:	class=0x060100 rev=0x51 hdr=0x00 vendor=0x1022 device=0x790e subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'FCH LPC Bridge'
    class      = bridge
    subclass   = PCI-ISA
hostb7@pci0:0:24:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1460 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 0'
    class      = bridge
    subclass   = HOST-PCI
hostb8@pci0:0:24:1:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1461 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 1'
    class      = bridge
    subclass   = HOST-PCI
hostb9@pci0:0:24:2:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1462 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 2'
    class      = bridge
    subclass   = HOST-PCI
hostb10@pci0:0:24:3:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1463 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 3'
    class      = bridge
    subclass   = HOST-PCI
hostb11@pci0:0:24:4:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1464 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 4'
    class      = bridge
    subclass   = HOST-PCI
hostb12@pci0:0:24:5:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1465 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 5'
    class      = bridge
    subclass   = HOST-PCI
hostb13@pci0:0:24:6:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1466 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 6'
    class      = bridge
    subclass   = HOST-PCI
hostb14@pci0:0:24:7:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1467 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 7'
    class      = bridge
    subclass   = HOST-PCI
nvme0@pci0:1:0:0:	class=0x010802 rev=0x03 hdr=0x00 vendor=0x1cc1 device=0x8201 subvendor=0x1cc1 subdevice=0x8201
    vendor     = 'ADATA Technology Co., Ltd.'
    device     = 'XPG SX8200 Pro PCIe Gen3x4 M.2 2280 Solid State Drive'
    class      = mass storage
    subclass   = NVM
xhci0@pci0:2:0:0:	class=0x0c0330 rev=0x02 hdr=0x00 vendor=0x1022 device=0x43bb subvendor=0x1b21 subdevice=0x1142
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = '300 Series Chipset USB 3.1 xHCI Controller'
    class      = serial bus
    subclass   = USB
ahci0@pci0:2:0:1:	class=0x010601 rev=0x02 hdr=0x00 vendor=0x1022 device=0x43b7 subvendor=0x1b21 subdevice=0x1062
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = '300 Series Chipset SATA Controller'
    class      = mass storage
    subclass   = SATA
pcib3@pci0:2:0:2:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x1022 device=0x43b2 subvendor=0x1b21 subdevice=0x0201
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    class      = bridge
    subclass   = PCI-PCI
pcib4@pci0:3:0:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x1022 device=0x43b4 subvendor=0x1b21 subdevice=0x3306
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = '300 Series Chipset PCIe Port'
    class      = bridge
    subclass   = PCI-PCI
pcib5@pci0:3:1:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x1022 device=0x43b4 subvendor=0x1b21 subdevice=0x3306
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = '300 Series Chipset PCIe Port'
    class      = bridge
    subclass   = PCI-PCI
pcib7@pci0:3:4:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x1022 device=0x43b4 subvendor=0x1b21 subdevice=0x3306
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = '300 Series Chipset PCIe Port'
    class      = bridge
    subclass   = PCI-PCI
pcib8@pci0:3:6:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x1022 device=0x43b4 subvendor=0x1b21 subdevice=0x3306
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = '300 Series Chipset PCIe Port'
    class      = bridge
    subclass   = PCI-PCI
pcib9@pci0:3:7:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x1022 device=0x43b4 subvendor=0x1b21 subdevice=0x3306
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = '300 Series Chipset PCIe Port'
    class      = bridge
    subclass   = PCI-PCI
pcib6@pci0:5:0:0:	class=0x060400 rev=0x04 hdr=0x01 vendor=0x1b21 device=0x1080 subvendor=0x1043 subdevice=0x8489
    vendor     = 'ASMedia Technology Inc.'
    device     = 'ASM1083/1085 PCIe to PCI Bridge'
    class      = bridge
    subclass   = PCI-PCI
nvme1@pci0:7:0:0:	class=0x010802 rev=0x03 hdr=0x00 vendor=0x1cc1 device=0x8201 subvendor=0x1cc1 subdevice=0x8201
    vendor     = 'ADATA Technology Co., Ltd.'
    device     = 'XPG SX8200 Pro PCIe Gen3x4 M.2 2280 Solid State Drive'
    class      = mass storage
    subclass   = NVM
em0@pci0:9:0:0:	class=0x020000 rev=0x00 hdr=0x00 vendor=0x8086 device=0x10d3 subvendor=0x8086 subdevice=0xa01f
    vendor     = 'Intel Corporation'
    device     = '82574L Gigabit Network Connection'
    class      = network
    subclass   = ethernet
vgapci0@pci0:10:0:0:	class=0x030000 rev=0xef hdr=0x00 vendor=0x1002 device=0x67df subvendor=0x148c subdevice=0x2379
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]'
    class      = display
    subclass   = VGA
hdac0@pci0:10:0:1:	class=0x040300 rev=0x00 hdr=0x00 vendor=0x1002 device=0xaaf0 subvendor=0x148c subdevice=0xaaf0
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]'
    class      = multimedia
    subclass   = HDA
none0@pci0:11:0:0:	class=0x130000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x145a subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Zeppelin/Raven/Raven2 PCIe Dummy Function'
    class      = non-essential instrumentation
none1@pci0:11:0:2:	class=0x108000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1456 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) Platform Security Processor'
    class      = encrypt/decrypt
xhci1@pci0:11:0:3:	class=0x0c0330 rev=0x00 hdr=0x00 vendor=0x1022 device=0x145c subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) USB 3.0 Host Controller'
    class      = serial bus
    subclass   = USB
none2@pci0:12:0:0:	class=0x130000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1455 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Zeppelin/Renoir PCIe Dummy Function'
    class      = non-essential instrumentation
ahci1@pci0:12:0:2:	class=0x010601 rev=0x51 hdr=0x00 vendor=0x1022 device=0x7901 subvendor=0x1043 subdevice=0x8747
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'FCH SATA Controller [AHCI mode]'
    class      = mass storage
    subclass   = SATA
hdac1@pci0:12:0:3:	class=0x040300 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1457 subvendor=0x1043 subdevice=0x86c7
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Family 17h (Models 00h-0fh) HD Audio Controller'
    class      = multimedia
    subclass   = HDA

</details>

**DRM KMOD version**
Paste the output of `pkg query -x '%n %v' 'drm.*kmod'`

$ pkg query -x '%n %v' 'drm.*kmod'
$ 

**To Reproduce**
Steps to reproduce the behavior: kldload amdgpu

**Screenshots**

**Additional context**
I can still login via ssh - kernel messages from the amdgpu driver:

[drm] amdgpu kernel modesetting enabled.
drmn0: <drmn> on vgapci0
vgapci0: child drmn0 requested pci_enable_io
vgapci0: child drmn0 requested pci_enable_io
[drm] initializing kernel modesetting (POLARIS10 0x1002:0x67DF 0x148C:0x2379 0xEF).
drmn0: Trusted Memory Zone (TMZ) feature not supported
[drm] register mmio base: 0xFCE00000
[drm] register mmio size: 262144
[drm] add ip block number 0 <vi_common>
[drm] add ip block number 1 <gmc_v8_0>
[drm] add ip block number 2 <tonga_ih>
[drm] add ip block number 3 <gfx_v8_0>
[drm] add ip block number 4 <sdma_v3_0>
[drm] add ip block number 5 <powerplay>
[drm] add ip block number 6 <dm>
[drm] add ip block number 7 <uvd_v6_0>
[drm] add ip block number 8 <vce_v3_0>
drmn0: Fetched VBIOS from ROM BAR
amdgpu: ATOM BIOS: 113-D0003400_100
[drm] UVD is enabled in VM mode
[drm] UVD ENC is enabled in VM mode
[drm] VCE enabled in VM mode
[drm] vm size is 64 GB, 2 levels, block size is 10-bit, fragment size is 9-bit
drmn0: successfully loaded firmware image 'amdgpu/polaris10_mc.bin'
drmn0: VRAM: 4096M 0x000000F400000000 - 0x000000F4FFFFFFFF (4096M used)
drmn0: GART: 256M 0x000000FF00000000 - 0x000000FF0FFFFFFF
[drm] Detected VRAM RAM=4096M, BAR=256M
[drm] RAM width 256bits GDDR5
[TTM] Zone  kernel: Available graphics memory: 8332866 KiB
[TTM] Zone   dma32: Available graphics memory: 2097152 KiB
[TTM] Initializing pool allocator
[drm] amdgpu: 4096M of VRAM memory ready
[drm] amdgpu: 4096M of GTT memory ready.
[drm] GART: num cpu pages 65536, num gpu pages 65536
[drm] PCIE GART of 256M enabled (table at 0x000000F400300000).
drmn0: successfully loaded firmware image 'amdgpu/polaris10_pfp_2.bin'
drmn0: successfully loaded firmware image 'amdgpu/polaris10_me_2.bin'
drmn0: successfully loaded firmware image 'amdgpu/polaris10_ce_2.bin'
[drm] Chained IB support enabled!
drmn0: successfully loaded firmware image 'amdgpu/polaris10_rlc.bin'
drmn0: successfully loaded firmware image 'amdgpu/polaris10_mec_2.bin'
drmn0: successfully loaded firmware image 'amdgpu/polaris10_mec2_2.bin'
drmn0: successfully loaded firmware image 'amdgpu/polaris10_sdma.bin'
drmn0: successfully loaded firmware image 'amdgpu/polaris10_sdma1.bin'
amdgpu: hwmgr_sw_init smu backed is polaris10_smu
drmn0: successfully loaded firmware image 'amdgpu/polaris10_uvd.bin'
[drm] Found UVD firmware Version: 1.130 Family ID: 16
drmn0: successfully loaded firmware image 'amdgpu/polaris10_vce.bin'
[drm] Found VCE firmware Version: 53.26 Binary ID: 3
drmn0: successfully loaded firmware image 'amdgpu/polaris10_k_smc.bin'
amdgpu: 
 failed to send message 136 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 53 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 169 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 185 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 187 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 188 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 10a ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 305 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 26a ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 415 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 209 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 206 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 5b ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 205 ret is 65535 
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 20a ret is 65535 
[drm ERROR :update_num_audio] DC: unexpected audio fuse!
[drm] DM_PPLIB: values for Engine clock
[drm] DM_PPLIB:	 300000
[drm] DM_PPLIB:	 588000
[drm] DM_PPLIB:	 952000
[drm] DM_PPLIB:	 1046000
[drm] DM_PPLIB:	 1112000
[drm] DM_PPLIB:	 1174000
[drm] DM_PPLIB:	 1215000
[drm] DM_PPLIB:	 1250000
[drm] DM_PPLIB: Validation clocks:
[drm] DM_PPLIB:    engine_max_clock: 125000
[drm] DM_PPLIB:    memory_max_clock: 175000
[drm] DM_PPLIB:    level           : 8
[drm] DM_PPLIB: values for Memory clock
[drm] DM_PPLIB:	 300000
[drm] DM_PPLIB:	 1000000
[drm] DM_PPLIB:	 1750000
[drm] DM_PPLIB: Validation clocks:
[drm] DM_PPLIB:    engine_max_clock: 125000
[drm] DM_PPLIB:    memory_max_clock: 175000
[drm] DM_PPLIB:    level           : 8
[drm] Display Core initialized with v3.2.104!
lkpi_iic0: <LinuxKPI I2C> on drmn0
iicbus0: <Philips I2C bus> on lkpi_iic0
iic0: <I2C generic I/O> on iicbus0
[drm ERROR :dc_link_detect_helper] No EDID read.
lkpi_iic1: <LinuxKPI I2C> on drmn0
iicbus1: <Philips I2C bus> on lkpi_iic1
iic1: <I2C generic I/O> on iicbus1
[drm ERROR :dc_link_detect_helper] No EDID read.
lkpi_iic2: <LinuxKPI I2C> on drmn0
iicbus2: <Philips I2C bus> on lkpi_iic2
iic2: <I2C generic I/O> on iicbus2
[drm ERROR :dc_link_detect_helper] No EDID read.
lkpi_iic3: <LinuxKPI I2C> on drmn0
iicbus3: <Philips I2C bus> on lkpi_iic3
iic3: <I2C generic I/O> on iicbus3
[drm ERROR :dc_link_detect_helper] No EDID read.
lkpi_iic4: <LinuxKPI I2C> on drmn0
iicbus4: <Philips I2C bus> on lkpi_iic4
iic4: <I2C generic I/O> on iicbus4
[drm ERROR :dc_link_detect_helper] No EDID read.
amdgpu: 
 last message was failed ret is 65535
amdgpu: 
 failed to send message 154 ret is 65535 
WARNING ring->wptr % 2 || count % 2 failed at /usr/home/gldisater/drm-next-module/kms-drm/drivers/gpu/drm/amd/amdgpu/uvd_v6_0.c:1080
drmn0: [drm] *ERROR* [drm ERROR :amdgpu_device_ip_hw_init_phase2] hw_init of IP block <uvd_v6_0> failed -60
drmn0: amdgpu_device_ip_init failed
drmn0: Fatal error during GPU init
device_attach: drmn0 attach returned 60

**Comment by evadot** [comment]
Do you still have this problem after updating to 5.15 or later ?

**Comment by evadot** [comment]
Closing as no news.
