### ISSUE TITLE
drmn.ko depends on acpi unconditionally

### ISSUE THREAD

**Issue by chmeeedalf** [freebsd/drm-kmod#214]
drmn.ko cannot be loaded on powerpc64 due to a dependency on acpi_iic_driver, yielding the following error message:

link_elf: symbol acpi_iicbus_driver undefined
KLD radeonkms.ko: depends on drmn - not available or version mismatch

The attached patch fixes this.

[fix_drm_ppc.diff.txt](https://github.com/freebsd/drm-kmod/files/9945014/fix_drm_ppc.diff.txt)

**Comment by evadot** [comment]
Fixed some time ago.

**Comment by pkubaj** [comment]
This issue is still relevant.
