### ISSUE TITLE
i915kms: artifacts with overlays on top of video playback in chromium+youtube

### ISSUE THREAD

**Issue by erikarn** [freebsd/drm-kmod#227]
**Describe the bug**

There are artifacts with overlays on top of video playback - with youtube, when watching videos it's fine, but when you mouse over the playback window to manipulate the controls, you end up with horizontal banding.

This didn't happen with the -HEAD install I had here from a few months ago. (Yes, if requested I can actually go grab the ports tree and FreeBSD-HEAD version as I still have the installation media..)

**FreeBSD version**

it's -HEAD, ff06a8dbb677a04 (Aug 19, 2022 commit from jhibbits, but  it's from the tree @ Jan 22 2023)

**PCI Info**

<details>
  <summary>pciconf -lv</summary>
  
(It's a Haswell-ULT - vendor 0x8086, device 0x0a26, subvendor 0x106b, subdevice 0x011b)

</details>

**DRM KMOD version**
drm-510-kmod 5.10.113_8

**To Reproduce**
* fire up xorg
* fire up chromium
* watch youtube :-)
* 
**Screenshots**
<img width="647" alt="Screen Shot 2023-01-27 at 7 27 18 PM" src="https://user-images.githubusercontent.com/1156589/215240044-4136ad1b-5d9a-4055-92c4-bb1ae62eeb29.png">
<img width="629" alt="Screen Shot 2023-01-27 at 7 27 14 PM" src="https://user-images.githubusercontent.com/1156589/215240051-1daa0cc6-2cdb-4c91-9a20-da9afee8a920.png">

**Additional context**

This is on both a macbookair6,1 and macbookair6,2, which are similar era computers.

**Comment by evadot** [comment]
Is this with libva-intel-driver installed ?
As said on irc this kind of regression is hard to track as it might be from drm or mesa or something else ...

**Comment by evadot** [comment]
Ping for the question about libva

**Comment by evadot** [comment]
Closing as no news.
