### ISSUE TITLE
amdgpu vaapi failure due to dma_resv_locking_ctx returning 0

### ISSUE THREAD

**Issue by myfreeweb** [freebsd/drm-kmod#32]
Finally got around to debugging the video acceleration on Vega again. (HEVC *encoding* was working, H264 encoding and ALL *decoding* broke at some point)

Turns out this "double check" is failing: https://github.com/freebsd/drm-kmod/blob/2b7442a5bc2a7209908a6697ac60bb81ad10b9a0/drivers/gpu/drm/amd/amdgpu/amdgpu_cs.c#L1730-L1732

because the `dma_resv_locking_ctx(..)` result is zero. Everything is working fine when the `return` is replaced with a `printf`.

---

how to reproduce: easiest command is `avcstreamoutdemo` (from libva utils) but it won't really be successful (still some assertion failure) when it's working, just the amdgpu error would disappear.

`mpv -v --hwdec=vaapi some-thing.mp4` (mp4 either h264 or hevc if `vainfo` lists hevc) should start working when fixed

**Comment by myfreeweb** [comment]
Looking a bit deeper..

```
dma_resv_locking_ctx == READ_ONCE(obj->lock.ctx)
struct dma_resv *obj -> struct ww_mutex lock
```

```c
struct ww_acquire_ctx {
};
struct ww_mutex {
	struct mutex base;
	struct cv condvar;
	struct ww_acquire_ctx *ctx;
};
```

there is no 'ctx =' in `ww_mutex.h`, seems like nothing ever sets that field. `ww_mutex_lock(_interruptible)` just ignores the `ctx` argument! I'll try setting it there.

**Comment by myfreeweb** [comment]
https://reviews.freebsd.org/D26657

**Comment by evadot** [comment]
So this can be closed now that it's commited ?

**Comment by myfreeweb** [comment]
Yep
