### ISSUE TITLE
System updates break on drm-kmod

### ISSUE THREAD

**Issue by m-ildefons** [freebsd/drm-kmod#44]
Dear maintainers,

I updated from 12.1-RELEASE to 12.2-RELEASE and could not properly complete the procedure, because after the first reboot, the system does not come up to a shell. The error messages where not decipherable because the system output was scrambled.

I then had to reboot the old kernel, disable loading the `i915kms` kernel module (in my case) and then I could boot the new kernel, remove the `drm-kmod` and `drm-fbsd12.0-kmod` packages via `pkg`, build the ports and only then I could complete the update.
All of this was only possible after I had spent way too much time searching through vaguely related forum threads.
As some users reported on IRC, this has happened with several releases in the past.

I have two issues with that:
1) Is there a way to have the proper package ready with the new release in order to avoid having to use ports?
2) Is there a way to document this?

I may sound like I am only complaining here, but I'd actually like to help out if I can. I don't know how though.

Relevant System Specs:
Intel i5-4200U (Intel® HD Graphics 4400)
FreeBSD 12.1-RELEASE/FreeBSD 12.2-RELEASE

**Comment by evadot** [comment]
The code in this repository doesn't support 12.X only 13-CURRENT and above.
Please open a bug https://github.com/FreeBSDDesktop/kms-drm
