### ISSUE TITLE
Vulkan app frozen after DPMS

### ISSUE THREAD

**Issue by evadot** [freebsd/drm-kmod#5]
On my AMD Ryzen 7 with a Picasso GPU (RAVEN/VEGA10) vulkan apps do not redraw after waking up the screen.
No idea if it was always the case of if it's recent.

**Comment by evadot** [comment]
Reopen as it's not solved.

**Comment by khodek** [comment]
Reminds me of this: https://gitlab.freedesktop.org/mesa/mesa/-/commit/a60767ec266a06fe04362c4df715d467e155a8dc

**Comment by evadot** [comment]
Works with v5.10 after DPMS and suspend/resume so closing this again and let's keep it working.
