### ISSUE TITLE
The next big release should be 5.11

### ISSUE THREAD

**Issue by zoujiaqing** [freebsd/drm-kmod#53]
1. AMD Radeon Graphics Updates For Linux 5.11 Bring New Hardware ( for AMD RX6000 GPU)
2. Intel Xe Graphics Are Looking Great On Linux 5.11 With Nice Performance Uplift
3. NVIDIA RTX 30 "Ampere" Support In Linux 5.11 (with kmod)

**Comment by evadot** [comment]
Not an issue, closing.
