### ISSUE TITLE
panic on 14-CURRENT with AMD NAVI10

### ISSUE THREAD

**Issue by thisplacestinksoffascism** [freebsd/drm-kmod#64]
**Describe the bug**
System panics when issuing `sysctl -a`

**FreeBSD version**
FreeBSD direwolf.local. 14.0-CURRENT FreeBSD 14.0-CURRENT #0 main-n245338-221622ec0c8-dirty: Tue Mar  9 15:30:10 AWST 2021     agh@direwolf.local.:/tmp/direwolf/usr/src/amd64.amd64/sys/DIREWOLF_DEBUG  amd64

dirty because of:

```
index 30d6d94723f..fbcd176457d 100644
--- a/sbin/sysctl/sysctl.c
+++ b/sbin/sysctl/sysctl.c
@@ -336,6 +336,12 @@ parse_numeric(const char *newvalstr, const char *fmt, u_int kind,
        return (true);
 }

+/*
+#define                sysctl(...) ({ \
+       usleep(100000); \
+       sysctl(__VA_ARGS__); })
+*/
+
```

Which is used for debugging this panic.

**PCI Info**

hostb0@pci0:0:0:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1480 subvendor=0x1022 subdevice=0x1480
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse Root Complex'
    class      = bridge
    subclass   = HOST-PCI
none0@pci0:0:0:2:	class=0x080600 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1481 subvendor=0x1022 subdevice=0x1481
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse IOMMU'
    class      = base peripheral
    subclass   = IOMMU
hostb1@pci0:0:1:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1482 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib1@pci0:0:1:2:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1483 subvendor=0x1022 subdevice=0x1453
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
hostb2@pci0:0:2:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1482 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
hostb3@pci0:0:3:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1482 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib14@pci0:0:3:1:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1483 subvendor=0x1022 subdevice=0x1453
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
hostb4@pci0:0:4:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1482 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
hostb5@pci0:0:5:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1482 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
hostb6@pci0:0:7:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1482 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib17@pci0:0:7:1:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1484 subvendor=0x1022 subdevice=0x1484
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]'
    class      = bridge
    subclass   = PCI-PCI
hostb7@pci0:0:8:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1482 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Host Bridge'
    class      = bridge
    subclass   = HOST-PCI
pcib18@pci0:0:8:1:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x1484 subvendor=0x1022 subdevice=0x1484
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]'
    class      = bridge
    subclass   = PCI-PCI
intsmb0@pci0:0:20:0:	class=0x0c0500 rev=0x61 hdr=0x00 vendor=0x1022 device=0x790b subvendor=0x1849 subdevice=0xffff
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'FCH SMBus Controller'
    class      = serial bus
    subclass   = SMBus
isab0@pci0:0:20:3:	class=0x060100 rev=0x51 hdr=0x00 vendor=0x1022 device=0x790e subvendor=0x1849 subdevice=0xffff
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'FCH LPC Bridge'
    class      = bridge
    subclass   = PCI-ISA
hostb8@pci0:0:24:0:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1440 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 0'
    class      = bridge
    subclass   = HOST-PCI
hostb9@pci0:0:24:1:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1441 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 1'
    class      = bridge
    subclass   = HOST-PCI
hostb10@pci0:0:24:2:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1442 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 2'
    class      = bridge
    subclass   = HOST-PCI
hostb11@pci0:0:24:3:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1443 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 3'
    class      = bridge
    subclass   = HOST-PCI
hostb12@pci0:0:24:4:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1444 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 4'
    class      = bridge
    subclass   = HOST-PCI
hostb13@pci0:0:24:5:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1445 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 5'
    class      = bridge
    subclass   = HOST-PCI
hostb14@pci0:0:24:6:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1446 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 6'
    class      = bridge
    subclass   = HOST-PCI
hostb15@pci0:0:24:7:	class=0x060000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1447 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Device 24: Function 7'
    class      = bridge
    subclass   = HOST-PCI
pcib2@pci0:1:0:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x57ad subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse Switch Upstream'
    class      = bridge
    subclass   = PCI-PCI
pcib3@pci0:2:1:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x57a3 subvendor=0x1022 subdevice=0x1453
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
pcib4@pci0:2:3:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x57a3 subvendor=0x1022 subdevice=0x1453
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
pcib9@pci0:2:5:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x57a3 subvendor=0x1022 subdevice=0x1453
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
pcib11@pci0:2:8:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x57a4 subvendor=0x1022 subdevice=0x1484
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
pcib12@pci0:2:9:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x57a4 subvendor=0x1022 subdevice=0x1484
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
pcib13@pci0:2:10:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1022 device=0x57a4 subvendor=0x1022 subdevice=0x1484
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse PCIe GPP Bridge'
    class      = bridge
    subclass   = PCI-PCI
igb0@pci0:3:0:0:	class=0x020000 rev=0x01 hdr=0x00 vendor=0x8086 device=0x1521 subvendor=0x8086 subdevice=0x0002
    vendor     = 'Intel Corporation'
    device     = 'I350 Gigabit Network Connection'
    class      = network
    subclass   = ethernet
igb1@pci0:3:0:1:	class=0x020000 rev=0x01 hdr=0x00 vendor=0x8086 device=0x1521 subvendor=0x8086 subdevice=0x0002
    vendor     = 'Intel Corporation'
    device     = 'I350 Gigabit Network Connection'
    class      = network
    subclass   = ethernet
pcib5@pci0:5:0:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1b21 device=0x1184 subvendor=0x1849 subdevice=0x1184
    vendor     = 'ASMedia Technology Inc.'
    device     = 'ASM1184e PCIe Switch Port'
    class      = bridge
    subclass   = PCI-PCI
pcib6@pci0:6:3:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1b21 device=0x1184 subvendor=0x1849 subdevice=0x1184
    vendor     = 'ASMedia Technology Inc.'
    device     = 'ASM1184e PCIe Switch Port'
    class      = bridge
    subclass   = PCI-PCI
pcib7@pci0:6:5:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1b21 device=0x1184 subvendor=0x1849 subdevice=0x1184
    vendor     = 'ASMedia Technology Inc.'
    device     = 'ASM1184e PCIe Switch Port'
    class      = bridge
    subclass   = PCI-PCI
pcib8@pci0:6:7:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1b21 device=0x1184 subvendor=0x1849 subdevice=0x1184
    vendor     = 'ASMedia Technology Inc.'
    device     = 'ASM1184e PCIe Switch Port'
    class      = bridge
    subclass   = PCI-PCI
igb2@pci0:8:0:0:	class=0x020000 rev=0x03 hdr=0x00 vendor=0x8086 device=0x1539 subvendor=0x1849 subdevice=0x1539
    vendor     = 'Intel Corporation'
    device     = 'I211 Gigabit Network Connection'
    class      = network
    subclass   = ethernet
pcib10@pci0:10:0:0:	class=0x060400 rev=0x04 hdr=0x01 vendor=0x1b21 device=0x1080 subvendor=0x0000 subdevice=0x0000
    vendor     = 'ASMedia Technology Inc.'
    device     = 'ASM1083/1085 PCIe to PCI Bridge'
    class      = bridge
    subclass   = PCI-PCI
fwohci0@pci0:11:4:0:	class=0x0c0010 rev=0x01 hdr=0x00 vendor=0x104c device=0x8025 subvendor=0x0f2e subdevice=0x8025
    vendor     = 'Texas Instruments'
    device     = 'TSB82AA2 IEEE-1394b Link Layer Controller'
    class      = serial bus
    subclass   = FireWire
none1@pci0:12:0:0:	class=0x130000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1485 subvendor=0x1022 subdevice=0x1485
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse Reserved SPP'
    class      = non-essential instrumentation
xhci0@pci0:12:0:1:	class=0x0c0330 rev=0x00 hdr=0x00 vendor=0x1022 device=0x149c subvendor=0x1022 subdevice=0x1486
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse USB 3.0 Host Controller'
    class      = serial bus
    subclass   = USB
xhci1@pci0:12:0:3:	class=0x0c0330 rev=0x00 hdr=0x00 vendor=0x1022 device=0x149c subvendor=0x1022 subdevice=0x148c
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse USB 3.0 Host Controller'
    class      = serial bus
    subclass   = USB
ahci0@pci0:13:0:0:	class=0x010601 rev=0x51 hdr=0x00 vendor=0x1022 device=0x7901 subvendor=0x1022 subdevice=0x7901
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'FCH SATA Controller [AHCI mode]'
    class      = mass storage
    subclass   = SATA
ahci1@pci0:14:0:0:	class=0x010601 rev=0x51 hdr=0x00 vendor=0x1022 device=0x7901 subvendor=0x1022 subdevice=0x7901
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'FCH SATA Controller [AHCI mode]'
    class      = mass storage
    subclass   = SATA
pcib15@pci0:15:0:0:	class=0x060400 rev=0xc1 hdr=0x01 vendor=0x1002 device=0x1478 subvendor=0x0000 subdevice=0x0000
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Navi 10 XL Upstream Port of PCI Express Switch'
    class      = bridge
    subclass   = PCI-PCI
pcib16@pci0:16:0:0:	class=0x060400 rev=0x00 hdr=0x01 vendor=0x1002 device=0x1479 subvendor=0x1002 subdevice=0x1479
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Navi 10 XL Downstream Port of PCI Express Switch'
    class      = bridge
    subclass   = PCI-PCI
vgapci0@pci0:17:0:0:	class=0x030000 rev=0xc1 hdr=0x00 vendor=0x1002 device=0x731f subvendor=0x1462 subdevice=0x3810
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]'
    class      = display
    subclass   = VGA
hdac0@pci0:17:0:1:	class=0x040300 rev=0x00 hdr=0x00 vendor=0x1002 device=0xab38 subvendor=0x1002 subdevice=0xab38
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Navi 10 HDMI Audio'
    class      = multimedia
    subclass   = HDA
none2@pci0:18:0:0:	class=0x130000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x148a subvendor=0x1022 subdevice=0x148a
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse PCIe Dummy Function'
    class      = non-essential instrumentation
none3@pci0:19:0:0:	class=0x130000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1485 subvendor=0x1022 subdevice=0x1485
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse Reserved SPP'
    class      = non-essential instrumentation
none4@pci0:19:0:1:	class=0x108000 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1486 subvendor=0x1022 subdevice=0x1486
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse Cryptographic Coprocessor PSPCPP'
    class      = encrypt/decrypt
xhci2@pci0:19:0:3:	class=0x0c0330 rev=0x00 hdr=0x00 vendor=0x1022 device=0x149c subvendor=0x1849 subdevice=0xffff
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Matisse USB 3.0 Host Controller'
    class      = serial bus
    subclass   = USB
hdac1@pci0:19:0:4:	class=0x040300 rev=0x00 hdr=0x00 vendor=0x1022 device=0x1487 subvendor=0x1849 subdevice=0x2221
    vendor     = 'Advanced Micro Devices, Inc. [AMD]'
    device     = 'Starship/Matisse HD Audio Controller'
    class      = multimedia
    subclass   = HDA

**DRM KMOD version**

drm-devel-kmod 5.4.92.g20210128_1

**To Reproduce**
sysctl -a

**Additional context**

https://docs.freebsd.org/cgi/getmsg.cgi?fetch=202014+0+archive/2021/freebsd-current/20210207.freebsd-current

**Comment by hselasky** [comment]
> Always panics at:
> $ /tmp/sysctl-with-delay -a
> [...]
> p1003_1b.mapped_files: 200112
> p1003_1b.memlock: 0
> p1003_1b.memlock_range: 0
> p1003_1b.memory_protection: 0
> p1003_1b.message_passing: 0
> p1003_1b.prioritized_io: 0
> p1003_1b.priority_scheduling: 200112
> p1003_1b.realtime_signals: 200112
> p1003_1b.semaphores: 0
> p1003_1b.fsync: 200112
> p1003_1b.shared_memory_objects: 200112
> p1003_1b.synchronized_io: 0
> p1003_1b.timers: 200112
> p1003_1b.aio_listio_max: 256
> p1003_1b.aio_max: 1024
> p1003_1b.aio_prio_delta_max: 0
> p1003_1b.delaytimer_max: 2147483647
> p1003_1b.mq_open_max: 0
> p1003_1b.pagesize: 4096
> p1003_1b.rtsig_max: 62
> p1003_1b.sem_nsems_max: 0
> p1003_1b.sem_value_max: 0
> p1003_1b.sigqueue_max: 128
> p1003_1b.timer_max: 32
>

Hi,

On my system:

p1003_1b.timer_max: 32
sys.class.drm.card0-HDMI-A-1.modes: 1680x1050
1600x1200
1280x1024
1440x900
1280x960
1024x768
800x600
640x480
720x400

So that means some modes sysctl is causing the panic.

**Comment by hselasky** [comment]
@evadot

**Comment by unrelentingtech** [comment]
Is this #15 / #41 again? The last comment in #15 says @evadot didn't do the promised cherry-pick of the upstream fix for that :)

**Comment by hselasky** [comment]
@unrelentingtech : Looks very similar!

**Comment by evadot** [comment]
The fixing commit is now in 5.4-lts, if you could try again.
Thanks

**Comment by thisplacestinksoffascism** [comment]
Works great on 14.0-CURRENT #0 main-n245400-e75eac2cb81
```
$ sysctl sys.class.drm
sys.class.drm.card0-HDMI-A-1.modes: 
sys.class.drm.card0-HDMI-A-1.dpms: Off
sys.class.drm.card0-HDMI-A-1.enabled: disabled
sys.class.drm.card0-HDMI-A-1.status: disconnected
sys.class.drm.card0-DP-3.modes: 
sys.class.drm.card0-DP-3.dpms: Off
sys.class.drm.card0-DP-3.enabled: disabled
sys.class.drm.card0-DP-3.status: disconnected
sys.class.drm.card0-DP-2.modes: 2560x1440
2560x1440
2560x1440
2560x1440
1920x1200
1920x1080
1920x1080
1920x1080
1920x1080
1920x1080
1600x1200
1680x1050
1600x900
1280x1024
1280x1024
1440x900
1280x800
1152x864
1280x720
1280x720
1280x720
1280x720
1024x768
1024x768
800x600
800x600
720x480
720x480
640x480
640x480
640x480
640x480
sys.class.drm.card0-DP-2.dpms: On
sys.class.drm.card0-DP-2.enabled: enabled
sys.class.drm.card0-DP-2.status: connected
sys.class.drm.card0-DP-1.modes: 2560x1440
2560x1440
2560x1440
2560x1440
1920x1200
1920x1080
1920x1080
1920x1080
1920x1080
1920x1080
1600x1200
1680x1050
1600x900
1280x1024
1280x1024
1440x900
1280x800
1152x864
1280x720
1280x720
1280x720
1280x720
1024x768
1024x768
800x600
800x600
720x480
720x480
640x480
640x480
640x480
640x480
sys.class.drm.card0-DP-1.dpms: On
sys.class.drm.card0-DP-1.enabled: enabled
sys.class.drm.card0-DP-1.status: connected
sys.class.drm.ttm.buffer_objects.bo_count: 394
sys.class.drm.ttm.memory_accounting.pool.pool_allocation_size: 2048
sys.class.drm.ttm.memory_accounting.pool.pool_small_allocation: 64
sys.class.drm.ttm.memory_accounting.pool.pool_max_size: 16752464
sys.class.drm.ttm.memory_accounting.dma32.used_memory: 8544
sys.class.drm.ttm.memory_accounting.dma32.swap_limit: 1572864
sys.class.drm.ttm.memory_accounting.dma32.available_memory: 2097152
sys.class.drm.ttm.memory_accounting.dma32.emergency_memory: 3145728
sys.class.drm.ttm.memory_accounting.dma32.zone_memory: 4194304
sys.class.drm.ttm.memory_accounting.kernel.used_memory: 64016
sys.class.drm.ttm.memory_accounting.kernel.swap_limit: 25128700
sys.class.drm.ttm.memory_accounting.kernel.available_memory: 33504934
sys.class.drm.ttm.memory_accounting.kernel.emergency_memory: 50257401
sys.class.drm.ttm.memory_accounting.kernel.zone_memory: 67009868
sys.class.drm.ttm.memory_accounting.lower_mem_limit: 0
sys.class.drm.version: drm 1.1.0 20060810
```

**Comment by evadot** [comment]
Thanks for testing, I'll update the ports this weekend probably.
