### ISSUE TITLE
How to merge code from Linux

### ISSUE THREAD

**Issue by neelchauhan** [freebsd/drm-kmod#70]
What is the process for merging code from Linux? I mean, which commands are used to merge and cherry pick commits from Linux to `drm-kmod`?

I'm interested in this mainly because I'm thinking about getting 5.5-wip working with i915kms (to support TigerLake), and am willing to do (at least some of) the dirty work myself. Maybe this will land into a PR.

**Comment by evadot** [comment]
You have two scripts in the scripts directory.
drmgeneratepatch will help you generate needed patches to go from one linux version to one other.
drmpatch will help you applying those patches.

**Comment by neelchauhan** [comment]
Thanks for letting me know. Sorry for the delayed response.

Closing this ticket.
