### ISSUE TITLE
adev->powerplay.pp_funcs  not set

### ISSUE THREAD

**Issue by sinetek** [freebsd/drm-kmod#74]
the bug is that "adev->powerplay.pp_funcs"  is not set. where is this normally set?
my chip is a Renoir one in the AMD Ryzen 5 4600H, vendor=0x1002 device=0x1636.

When I unplug or plug the power connector I get an ACPI event, which propagates to amdgpu_pm_acpi_event_handler,
which then wants to call the powerplay table

```
        if (adev->powerplay.pp_funcs->enable_bapm) {    <------ nasty crash
            amdgpu_dpm_enable_bapm(adev, adev->pm.ac_power);
        }


```

**Comment by sinetek** [comment]
Also want to thank a million for this amazing project. I'm looking at the code and can't believe what has been ported to FreeBSD, huge achievement this is.

**Comment by unrelentingtech** [comment]
We have the fix in 5.4-lts: https://github.com/freebsd/drm-kmod/commit/3ed2827cbc3601ea3836a4f431d02f7fc38dde0e so this one should be cherry-picked onto 5.5-wip

**Comment by sinetek** [comment]
wow that would have saved a lot of time, but i learned a lot hunting down
this bug.

id like to help
In general is it okay to sync portions of the code or should we only cherry
pick commits?

**Comment by evadot** [comment]
3ed2827 is in master and 5.7 (which is now drm-devel-kmod), closing the issue.
