### ISSUE TITLE
drm-kmod crash on i915kms when Xorg is loaded

### ISSUE THREAD

**Issue by neelchauhan** [freebsd/drm-kmod#81]
**Describe the bug**

When I load `i915kms` and then `gdm`, I get a coredump. This happens on the first boot, but not subsequent boots.

Coredump:
 * ~~[core.0.txt](https://github.com/freebsd/drm-kmod/files/6581781/core.0.txt)~~
 * [core.1.txt](https://github.com/freebsd/drm-kmod/files/6581911/core.1.txt)

I am using Xorg. The system is a HP Spectre x360 13-ap0053dx (WhiskeyLake).

**FreeBSD version**

    FreeBSD spectre.local 14.0-CURRENT FreeBSD 14.0-CURRENT #0 main-n246975-8d5c7813061: Thu May 27 09:39:01 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

**PCI Info**

    hostb0@pci0:0:0:0:	class=0x060000 rev=0x0b hdr=0x00 vendor=0x8086 device=0x3e34 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Coffee Lake HOST and DRAM Controller'
        class      = bridge
        subclass   = HOST-PCI
    vgapci0@pci0:0:2:0:	class=0x030000 rev=0x00 hdr=0x00 vendor=0x8086     device=0x3ea0 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'WhiskeyLake-U GT2 [UHD Graphics 620]'
        class      = display
        subclass   = VGA
    none0@pci0:0:4:0:	class=0x118000 rev=0x0b hdr=0x00 vendor=0x8086 device=0x1903 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem'
        class      = dasp
    pchtherm0@pci0:0:18:0:	class=0x118000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9df9 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP Thermal Controller'
        class      = dasp
    none1@pci0:0:19:0:	class=0x070000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9dfc subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP Integrated Sensor Hub'
        class      = simple comms
        subclass   = UART
    xhci0@pci0:0:20:0:	class=0x0c0330 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9ded subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP USB 3.1 xHCI Controller'
        class      = serial bus
        subclass   = USB
    none2@pci0:0:20:2:	class=0x050000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9def subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP Shared SRAM'
        class      = memory
        subclass   = RAM
    iwm0@pci0:0:20:3:	class=0x028000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9df0 subvendor=0x8086 subdevice=0x0034
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP CNVi [Wireless-AC]'
        class      = network
    ig4iic0@pci0:0:21:0:	class=0x0c8000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9de8 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP Serial IO I2C Controller'
        class      = serial bus
    ig4iic1@pci0:0:21:1:	class=0x0c8000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9de9 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP Serial IO I2C Controller'
        class      = serial bus
    none3@pci0:0:22:0:	class=0x078000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9de0 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP MEI Controller'
        class      = simple comms
    ahci0@pci0:0:23:0:	class=0x010400 rev=0x30 hdr=0x00 vendor=0x8086 device=0x282a subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = '82801 Mobile SATA Controller [RAID mode]'
        class      = mass storage
        subclass   = RAID
    pcib1@pci0:0:28:0:	class=0x060400 rev=0xf0 hdr=0x01 vendor=0x8086 device=0x9dba subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        class      = bridge
        subclass   = PCI-PCI
    pcib2@pci0:0:28:4:	class=0x060400 rev=0xf0 hdr=0x01 vendor=0x8086 device=0x9dbc subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP PCI Express Root Port'
        class      = bridge
        subclass   = PCI-PCI
    pcib8@pci0:0:29:0:	class=0x060400 rev=0xf0 hdr=0x01 vendor=0x8086 device=0x9db4 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP PCI Express Root Port'
        class      = bridge
        subclass   = PCI-PCI
    pcib9@pci0:0:29:6:	class=0x060400 rev=0xf0 hdr=0x01 vendor=0x8086 device=0x9db6 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP PCI Express Root Port'
        class      = bridge
        subclass   = PCI-PCI
    isab0@pci0:0:31:0:	class=0x060100 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9d84 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP LPC Controller'
        class      = bridge
        subclass   = PCI-ISA
    hdac0@pci0:0:31:3:	class=0x040100 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9dc8 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP High Definition Audio Controller'
        class      = multimedia
        subclass   = audio
    none4@pci0:0:31:4:	class=0x0c0500 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9da3 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP SMBus Controller'
        class      = serial bus
        subclass   = SMBus
    none5@pci0:0:31:5:	class=0x0c8000 rev=0x30 hdr=0x00 vendor=0x8086 device=0x9da4 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'Cannon Point-LP SPI Controller'
        class      = serial bus
    rtsx0@pci0:1:0:0:	class=0xff0000 rev=0x01 hdr=0x00 vendor=0x10ec device=0x525a subvendor=0x103c subdevice=0x8514
        vendor     = 'Realtek Semiconductor Co., Ltd.'
        device     = 'RTS525A PCI Express Card Reader'
    pcib3@pci0:2:0:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x8086 device=0x15d3 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]'
        class      = bridge
        subclass   = PCI-PCI
    pcib4@pci0:3:0:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x8086 device=0x15d3 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]'
        class      = bridge
        subclass   = PCI-PCI
    pcib5@pci0:3:1:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x8086 device=0x15d3 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]'
        class      = bridge
        subclass   = PCI-PCI
    pcib6@pci0:3:2:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x8086 device=0x15d3 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]'
        class      = bridge
        subclass   = PCI-PCI
    pcib7@pci0:3:4:0:	class=0x060400 rev=0x02 hdr=0x01 vendor=0x8086 device=0x15d3 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]'
        class      = bridge
        subclass   = PCI-PCI
    none6@pci0:4:0:0:	class=0x088000 rev=0x02 hdr=0x00 vendor=0x8086 device=0x15d2 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'JHL6540 Thunderbolt 3 NHI (C step) [Alpine Ridge 4C 2016]'
        class      = base peripheral
    xhci1@pci0:56:0:0:	class=0x0c0330 rev=0x02 hdr=0x00 vendor=0x8086 device=0x15d4 subvendor=0x103c subdevice=0x8514
        vendor     = 'Intel Corporation'
        device     = 'JHL6540 Thunderbolt 3 USB Controller (C step) [Alpine Ridge 4C 2016]'
        class      = serial bus
        subclass   = USB
    nvme0@pci0:109:0:0:	class=0x010802 rev=0x03 hdr=0x00 vendor=0x8086 device=0x0975 subvendor=0x8086 subdevice=0x8410
        vendor     = 'Intel Corporation'
        class      = mass storage
        subclass   = NVM
    nvme1@pci0:110:0:0:	class=0x010802 rev=0x00 hdr=0x00 vendor=0x8086 device=0x0975 subvendor=0x8086 subdevice=0x8510
        vendor     = 'Intel Corporation'
        class      = mass storage
        subclass   = NVM

</details>

**DRM KMOD version**

`5.5-wip` branch, but with cherry-picked `e5194b8949b316adfcda4895fc117cf1045d9336` and `b8a85669f61ffea54860a76f72b8c5c0bb647127` to unbreak the build.

**To Reproduce**

1. Checkout 5.5-wip branch.
2. Cherry pick commits `e5194b8949b316adfcda4895fc117cf1045d9336` and `b8a85669f61ffea54860a76f72b8c5c0bb647127` from `master`.
3. `make DEBUG_FLAGS=-g3` and `make install` the module
4. `kldload i915kms` and `gdm`
5. On the first boot, it should panic.

**Screenshots**

N/A.

**Additional context**

This happens (on my Spectre) on the first boot. Subsequent reboots after the first panic are not affected for me, and I can use gdm, gnome, firefox (WebGL fish), wine (Toontown Rewritten) normally.

@evadot has mentioned there is a crash when running Xorg or Weston, and I believe this is the same issue manifested differently.

**Comment by neelchauhan** [comment]
New coredump: [core.1.txt](https://github.com/freebsd/drm-kmod/files/6581911/core.1.txt)

Previous one lacked debugging symbols, sorry.

**Comment by evadot** [comment]
This have been fixed since.
Closing.
